ofds2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path, re_path
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('users.urls')),
    path('account/', include('account.urls')),
    re_path(r'^accounts/login/$', LoginView.as_view(template_name='registration/login.html'), name="login"),
    re_path(r'^accounts/logout/$', LogoutView.as_view(), LogoutView.next_page, name="logout"),
]

users/urls.py
from django.conf.urls import url
from . import views
from django.urls import path, re_path

app_name = 'users'
urlpatterns = [
    path('', views.home, name='home'),
    re_path(r'^home/$', views.home, name='home'),
    path('customer_list', views.customer_list, name='customer_list'),
    path('customer/create/', views.customer_add, name='customer_add'),
    path('customer/<int:pk>/edit/', views.customer_edit, name='customer_edit'),
    path('customer/<int:pk>/delete/', views.customer_delete, name='customer_delete'),
    path('item_list', views.item_list, name='item_list'),
    path('item/<int:pk>/edit/', views.item_edit, name='item_edit'),
    path('item/<int:pk>/delete/', views.item_delete, name='item_delete'),
    path('customer/<int:pk>/order_list/', views.order_list, name='order_list'),
    path('order/create/', views.order_add, name='order_add'),
    path('order/<int:pk>/edit/', views.order_edit, name='order_edit'),
    path('order/<int:pk>/delete/', views.order_delete, name='order_delete'),
    path('customer/order/<int:pk>/details/', views.order_detail_list, name='order_detail_list'),
    path('orderdetails/create/', views.order_details_add, name='order_details_add'),
    path('orderdetails/<int:pk>/delete/', views.order_details_delete, name='order_details_delete'),
]

users/models.py
from django.db import models

from django.utils import timezone


# Create your models here.
class Customer(models.Model):
    customer_number = models.IntegerField(blank=False, null=False)
    customer_fname = models.CharField(blank=False, max_length=50)
    customer_lname = models.CharField(max_length=50)
    customer_address_line1 = models.CharField(blank=False, max_length=200)
    customer_address_line2 = models.CharField(blank=True, max_length=200)
    customer_city = models.CharField(blank=False, max_length=50)
    customer_state = models.CharField(blank=False, max_length=50)
    customer_zipcode = models.CharField(blank=False, max_length=10)
    customer_email = models.EmailField(max_length=200)
    customer_cellphone = models.CharField(blank=False, max_length=50)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.customer_number)


class Item(models.Model):
    item_name = models.CharField(blank=False, max_length=50)
    item_description = models.CharField(max_length=500)
    item_price = models.CharField(blank=False, max_length=200)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.item_name)


class Order(models.Model):
    order_identity = models.CharField(max_length=100, blank=False)
    order_customer_name = models.ForeignKey(Customer, on_delete=models.CASCADE, related_name='orders')
    order_status = models.CharField(max_length=100, blank=False)
    order_total_cost = models.DecimalField(max_digits=10, decimal_places=2)
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.order_identity)


class OrderDetails(models.Model):
    detail_order_id = models.ForeignKey(Order, on_delete=models.CASCADE, related_name='orderid')
    detail_item_name = models.ForeignKey(Item, on_delete=models.CASCADE, related_name='itemname')
    detail_quantity = models.IntegerField(blank=False)
    detail_spice_level = models.IntegerField()
    created_date = models.DateTimeField(
        default=timezone.now)
    updated_date = models.DateTimeField(auto_now_add=True)

    def created(self):
        self.created_date = timezone.now()
        self.save()

    def updated(self):
        self.updated_date = timezone.now()
        self.save()

    def __str__(self):
        return str(self.detail_order_id)

users/forms.py
from django import forms
from .models import *

class CustomerForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ('customer_number', 'customer_fname', 'customer_lname', 'customer_address_line1', 'customer_address_line2', 'customer_city', 'customer_state', 'customer_zipcode', 'customer_email', 'customer_cellphone',)


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = ('item_name', 'item_description', 'item_price',)

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ('order_identity', 'order_customer_name', 'order_status', 'order_total_cost',)

class OrderDetailsForm(forms.ModelForm):
    class Meta:
        model = OrderDetails
        fields = ('detail_order_id', 'detail_item_name', 'detail_quantity', 'detail_spice_level',)

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from .models import *
from .forms import *
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect


now = timezone.now()
def home(request):
    return render(request, 'users/home.html',
                  {'users': home})

@login_required
def customer_list(request):
    customer = Customer.objects.filter(created_date__lte=timezone.now())
    return render(request, 'users/customer_list.html',
                  {'customers': customer})


@login_required
def customer_add(request):
   if request.method == "POST":
       form = CustomerForm(request.POST)
       if form.is_valid():
           customer = form.save(commit=False)
           customer.created_date = timezone.now()
           customer.save()
           customers = Customer.objects.filter(created_date__lte=timezone.now())
           return render(request, 'users/customer_list.html',
                         {'customers': customers})
   else:
       form = CustomerForm()
       # print("Else")
   return render(request, 'users/customer_add.html', {'form': form})



@login_required
def customer_edit(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    if request.method == "POST":
        # update
        form = CustomerForm(request.POST, instance=customer)
        if form.is_valid():
            customer = form.save(commit=False)
            customer.updated_date = timezone.now()
            customer.save()
            customer = Customer.objects.filter(created_date__lte=timezone.now())
            return render(request, 'users/customer_list.html',
                          {'customers': customer})
    else:
        # edit
        form = CustomerForm(instance=customer)
    return render(request, 'users/customer_edit.html', {'form': form})

@login_required
def customer_delete(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customer.delete()
    return redirect('users:customer_list')


@login_required
def item_list(request):
    item = Item.objects.filter(created_date__lte=timezone.now())
    return render(request, 'users/item_list.html',
                  {'items': item})

@login_required
def item_edit(request, pk):
    item = get_object_or_404(Item, pk=pk)
    if request.method == "POST":
        # update
        form = ItemForm(request.POST, instance=item)
        if form.is_valid():
            item = form.save(commit=False)
            item.updated_date = timezone.now()
            item.save()
            item = Item.objects.filter(created_date__lte=timezone.now())
            return render(request, 'users/item_list.html',
                          {'items': item})
    else:
        # edit
        form = ItemForm(instance=item)
    return render(request, 'users/item_edit.html', {'form': form})

@login_required
def item_delete(request, pk):
    item = get_object_or_404(Item, pk=pk)
    item.delete()
    return redirect('users:item_list')


@login_required
def order_list(request, pk):
    customer = get_object_or_404(Customer, pk=pk)
    customers = Customer.objects.filter(created_date__lte=timezone.now())
    orders = Order.objects.filter(order_customer_name=pk)
    return render(request, 'users/order_list.html', {'customers':customers, 'orders': orders})

@login_required
def order_add(request):
   if request.method == "POST":
       form = OrderForm(request.POST)
       if form.is_valid():
           order = form.save(commit=False)
           order.created_date = timezone.now()
           order.save()
           orders = Order.objects.filter(created_date__lte=timezone.now())
           return render(request, 'users/order_list.html',
                         {'orders': orders})
   else:
       form = OrderForm()
       # print("Else")
   return render(request, 'users/order_add.html', {'form': form})




@login_required
def order_edit(request, pk):
    order = get_object_or_404(Order, pk=pk)
    if request.method == "POST":
        # update
        form = OrderForm(request.POST, instance=order)
        if form.is_valid():
            order = form.save(commit=False)
            order.updated_date = timezone.now()
            order.save()
            order = Item.objects.filter(created_date__lte=timezone.now())
            return render(request, 'users/order_list.html',
                          {'orders': order})
    else:
        # edit
        form = OrderForm(instance=order)
    return render(request, 'users/order_edit.html', {'form': form})

@login_required
def order_delete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.delete()
    return redirect('users:customer_list')


@login_required
def order_detail_list(request, pk):
    order = get_object_or_404(Order, pk=pk)
    orders = Order.objects.filter(created_date__lte=timezone.now())
    orderdetails = OrderDetails.objects.filter(detail_order_id=pk)
    return render(request, 'users/order_detail_list.html', {'orders': orders, 'orderdetails': orderdetails})

@login_required
def order_details_add(request):
   if request.method == "POST":
       form = OrderDetailsForm(request.POST)
       if form.is_valid():
           orderdetail = form.save(commit=False)
           orderdetail.created_date = timezone.now()
           orderdetail.save()
           orderdetails = OrderDetails.objects.filter(created_date__lte=timezone.now())
           return redirect('users:customer_list')
           #return render(request, 'users/customer_list.html',
           #              {'orderdetails': orderdetails})
   else:
       form = OrderDetailsForm()
       # print("Else")
   return render(request, 'users/order_details_add.html', {'form': form})


@login_required
def order_details_delete(request, pk):
    orderdetails = get_object_or_404(OrderDetails, pk=pk)
    orderdetails.delete()
    return redirect('users:customer_list')

users/templates/users/base.html
{% load static %}

<html lang="en">
<head>
    <title>Online Food Delivery Service</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Set height of the grid so .sidenav can be 100% (adjust as needed) */
        .row.content {
            height: 450px
        }

        /* Set gray background color and 100% height */
        .sidenav {
            padding-top: 20px;
            background-color: #f1f1f1;
            height: 100%;
        }
        /* Set black background color, white text and some padding */
        footer {
            background-color: #555;
            color: white;
            padding: 15px;
        }

        /* On small screens, set height to 'auto' for sidenav and grid */
        @media screen and (max-width: 767px) {
            .sidenav {
                height: auto;
                padding: 15px;
            }

            .row.content {
                height: auto;
            }
        }
    </style>
</head>
<body id="app-layout">
<nav class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">

            <!-- Collapsed Hamburger -->
            <button type="button" class="navbar-toggle" data-toggle="collapse"
                    data-target="#myNavbar">
                <span class="sr-only">Toggle Navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- Branding Image -->
            <a class="navbar-brand" href="/">
                Online Food Delivery Service
            </a>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'users:home' %}">Home</a></li>
                <li><a href="{% url 'users:customer_list' %}">Customers</a></li>
                <li><a href="{% url 'users:item_list'%}">Menu</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                        <span class="caret"></span>
                    </a>
                    <ul class="dropdown-menu" role="menu">
                        <li><a href="{% url 'logout' %}"><i class="fa fa-btn fa-sign-out"></i>Logout</a></li>
                    </ul>
                </li>
                {% else %}
                <li><a href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="content container">
    <div class="row">
        <div class="col-md-8">
            {% block content %}
            <div class="links">
                <!-- Example row of columns -->
                <div class="row">
                    <div class="col-md-3">
                        <div class="thumbnail">
                            <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                            <div class="caption">
                                <h2>Customer</h2>
                                <p>Delighting customers and giving them a great dining experience is our main goal. </p>
                                {% if user.is_authenticated %}
                                <p><a class="btn btn-default" href="{% url 'users:customer_list' %}"
                                      role="button">View
                                    details &raquo;</a></p>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                    <div class="col-md-3">
                        <div class="thumbnail">
                            <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>
                            <div class="caption">
                                <h2>Menu</h2>
                                <p>Delicious dishes at affordable prices.</p>
                                <p><a class="btn btn-default" href="{% url 'users:item_list'%}"
                                      role="button">View
                                    details &raquo;</a></p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            {% endblock %}
        </div>
    </div>
</body>
</html>

users/templates/users/customer_add.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add a New Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

users/templates/users/customer_delete.html
{% extends 'users/base.html' %}
{% block body_block %}
    <h1>Delete {{ customer.customer_fname }} {{ customer.customer_lname }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'users:home' pk=customer.customer_number %} ">Cancel</a>
    </form>
{% endblock %}

users/templates/users/customer_edit.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Customer</h1>
    <form method="POST" class="customer-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

users/templates/users/home.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}

   <body>
    <html>
            {% if user.is_authenticated %}
                <div class="page-container">

                    <h2 class="top-menu">Hello {{ user.username }},</h2>
                    <p>Please choose from below options.</p>

                </div>
            {% endif %}
            <div class="content container">
                <div class="row">
                    <div class="col-md-12">
                        <div class="links">
                            <!-- Example row of columns -->
                            <div class="row">
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/customer.jpg" %}" alt="customer"/>
                                        <div class="caption">
                                            <h2>Customer</h2>
                                            <p>We see our success in our customers success </p>
                                            <p><a class="btn btn-primary" href="{% url 'users:customer_list' %}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-3">
                                    <div class="thumbnail">
                                        <img src="{% static "images/cupcakes.jpeg" %}" alt="cupcakes"/>
                                        <div class="caption">
                                            <h2>Menu</h2>
                                            <p>Great Dishes</p>
                                            <p><a class="btn btn-primary" href="{% url 'users:item_list'%}"
                                                  role="button">View
                                                details &raquo;</a></p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
    </body>
    </html>
{% endblock %}

users/templates/users/item_delete.html
{% extends 'users/base.html' %}
{% block body_block %}
    <h1>Delete {{ item.item_name }}?</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'users:home' pk=item.item_name %} ">Cancel</a>
    </form>
{% endblock %}

users/templates/users/item_edit.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Item</h1>
    <form method="POST" class="item-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

users/templates/users/item_list.html
{% extends 'users/base.html' %}
{% block content %}

    <html>
    <head>
        <meta charset="UTF-8">
        <title>Online Food Delivery Service</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Online Food Delivery Services.
                    </div>
                    </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Menu</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Item Name</th>
                <th>Item Description</th>
                <th>Item Price</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for item in items %}
                <tr>
                    <td>{{ item.item_name }}</td>
                    <td>{{ item.item_description }}</td>
                    <td>{{ item.item_price }}</td>

                    <td><a href="{% url 'users:item_edit' pk=item.pk %}" class="btn btn-warning">Edit</a>
                    <td><a href="{% url 'users:item_delete' pk=item.pk %}"
                           onclick="return confirm('Are you sure you want to delete?')"
                           class="btn btn-danger">Delete</a>
                    </td>

                </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
    </body>
    </html>
{% endblock %}

users/templates/users/order_delete.html
{% extends 'users/base.html' %}
{% block body_block %}
    <h1>Delete</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'users:home' pk=item.item_name %} ">Cancel</a>
    </form>
{% endblock %}

users/templates/users/order_detail_list.html
{% extends 'users/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Online Food Delivery Service</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Online Food Delivery Services.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Order Details</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Item Name</th>
                <th>Quantity</th>
                <th>Spice Level</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for orderdetails in orderdetails %}
                <tr>
                    <td>{{ orderdetails.detail_item_name }}</td>
                    <td>{{ orderdetails.detail_quantity }}</td>
                    <td>{{ orderdetails.detail_spice_level }}</td>
                    <td><a href="{% url 'users:order_details_delete' pk=orderdetails.pk %}"
                           class="btn btn-danger">Delete</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="row">
         <a href="{% url 'users:order_details_add' %}" class="row"><span
                    class="btn btn-primary">Add Order Details</span></a>
         </div>
    </div>
    </body>
    </html>
{% endblock %}s

users/templates/users/order_details_add.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Add New Order Details</h1>
    <form method="POST" class="order_details-form">{% csrf_token %}
          {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

users/templates/users/order_details_delete.html
{% extends 'users/base.html' %}
{% block body_block %}
    <h1>Delete</h1>

    <form method="post">
        {% csrf_token %}
        <input type="submit" class="btn btn-danger" value="Delete">
        <a href="{% url 'users:home' pk=item.item_name %} ">Cancel</a>
    </form>
{% endblock %}

users/templates/users/order_edit.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <h1>Edit Item</h1>
    <form method="POST" class="item-form">{% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="save btn btn-default">Update</button>
    </form>
{% endblock %}

users/templates/users/order_list.html
{% extends 'users/base.html' %}
{% block content %}
    <html>
    <head>
        <meta charset="UTF-8">
        <title>Online Food Delivery Service</title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">

    </head>
    <body>
    <style>
        body {
            background-color: beige;
        }
    </style>
    <div class="container">
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <div class="panel panel-primary">
                    <div class="panel-heading">Welcome!</div>
                    <div class="panel-body">
                        Online Food Delivery Services.
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <h2 style="padding-left: 15Px">Customer Orders</h2>
    </div>
    <div>
        <table class="table table-striped table-bordered table-hover">
            <thead>
            <tr class="bg-info">
                <th>Order Number</th>
                <th>Status</th>
                <th>Total Cost</th>
                <th colspan="3">Actions</th>
            </tr>
            </thead>
            <tbody>
            {% for order in orders %}
                <tr>
                    <td>{{ order.order_identity }}</td>
                    <td>{{ order.order_status }}</td>
                    <td>{{ order.order_total_cost }}</td>
                    <td><a href="{% url 'users:order_edit' pk=order.pk %}"
                           class="btn btn-warning">Edit</a></td>
                    <td><a href="{% url 'users:order_delete' pk=order.pk %}"
                           class="btn btn-danger">Delete</a>
                    </td>
                    <td><a href="{% url 'users:order_detail_list' pk=order.pk %}"
                           class="btn btn-primary">View Details</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="row">
         <a href="{% url 'users:order_add' %}" class="row"><span
                    class="btn btn-primary">Add Order</span></a>
         </div>

    </div>
    </body>
    </html>
{% endblock %}